Name: Pipeline

on:
    workflow_dispatch:
    pull_request:
        branches: ["main"]
        paths-ignore:
            - '**/*.md'
            - '**/*.gitignore'
            - '**/*.gitattributes'

jobs:
    build:
        name: Build
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v3

            - name: Setup .Net
              uses: actions/setup-dotnet@v2
              with:
                dotnet-version: 6.x

            #- name: Set Version
            #  uses: 

            - name: Restore
              run: dotnet restore
            
            - name: Build
              run: dotnet build --not-restore

            - name: Test
              run: dotnet test --no-build --no-restore --verbosity normal

            - name: Upload Artifacts
              uses: actions/upload-artifact@v3
              with:
                name: artifact
                if-no-files-found: error
                retention-days: 5
                path: |
                    ElgatoWaveAPI\bin\Release\netcoreapp3.1

    beta-publish:
        name: Beta Publish
        needs: build
        runs-on: windows-latest
        environment:
            name: beta
        steps:

            - name: Download Artifacts
              uses: actions/download-artifact@v3
              with:
                name: artifact
                path: artifactDownload

            #- name: Nugest Package

            #- name: Publich Nuget