name: Pipeline

on:
    workflow_dispatch:
    pull_request:
        branches: ["main"]
        paths-ignore:
            - '**/*.md'
            - '**/*.gitignore'
            - '**/*.gitattributes'

jobs:
    build:
        name: Build
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v3

            - name: Setup .Net
              uses: actions/setup-dotnet@v2
              with:
                dotnet-version: 6.x

            - name: Setup NuGet
              uses: nuget/setup-nuget@v1
              with:
                nuget-api-key: ${{secrets.NUGETAPI}}
                nuget-version: 5.x

            #- name: Set Version
            #  uses: 

            - name: Restore
              run: dotnet restore
            
            - name: Build
              run: dotnet build --configuration Release --no-restore --no-logo --version-suffix $GITHUB_RUN_NUMBER

            - name: Test
              run: dotnet test --no-build -c Release --no-restore --no-logo --collect "Code coverage" --blame

            - name: Upload Artifacts
              uses: actions/upload-artifact@v3
              with:
                name: artifact
                if-no-files-found: error
                retention-days: 5
                path: |
                    ElgatoWaveAPI\bin\Release\net6.0
                    ElgatoWaveAPI\bin\Release\*.nupkg

            - name: Publish Pre-Release
              run: nuget push "ElgatoWaveAPI\bin\Release\*.nupkg"

    beta-publish:
        name: Beta Publish
        needs: build
        runs-on: windows-latest
        environment:
            name: beta
        steps:

            - name: Download Artifacts
              uses: actions/download-artifact@v3
              with:
                name: artifact
                path: artifactDownload

            #- name: Nugest Package

            #- name: Publich Nuget

    release-publish:
        name: Release Publish
        needs: beta-publish
        runs-on: windows-latest
        environment:
            name: release
        steps:

            - name: Download Artifacts
              uses: actions/download-artifact@v3
              with:
                name: artifact
                path: artifactDownload

            #- name: Nugest Package

            #- name: Publich Nuget