name: Pipeline

on:
    workflow_dispatch:
    push:
        branches: ["main"]
        paths-ignore:
            - '**/*.md'
            - '**/*.gitignore'
            - '**/*.gitattributes'
    pull_request:
        paths-ignore:
            - '**/*.md'
            - '**/*.gitignore'
            - '**/*.gitattributes'

env:
    betaVersion:  beta

#Not sure if I want this to cancel the previous build yet
#concurrency:
#  group: ${{ github.workflow }}-${{ github.ref }}
#  cancel-in-progress: true

jobs:
    build:
        name: Build
        runs-on: windows-latest
        environment:
            name: pr
        steps:
            - uses: actions/checkout@v3

            - name: Ensure Version Change
              shell: pwsh
              run: |
                 .\VersionCheck.ps1

            - name: Setup .Net
              uses: actions/setup-dotnet@v2
              with:
                dotnet-version: 6.x

            - name: Restore
              run: dotnet restore

            - name: Build Beta
              run: dotnet build --configuration Release --no-restore

            - name: Test
              run: dotnet test --no-build -c Release --no-restore --collect "Code coverage" --blame

            - name: Upload Artifacts
              uses: actions/upload-artifact@v3
              with:
                name: artifact
                if-no-files-found: error
                retention-days: 5
                path: |
                    ElgatoWaveAPI/bin/Release/net6.0/*
              
    beta-release:
        name: Beta Release
        if: ${{ github.event_name != 'pull_request' }}
        runs-on: windows-latest
        needs: build
        environment:
            name: beta
        steps:
            - name: Download artifacts
              uses: actions/download-artifact@v3
              with:
                name: artifact
                path: ElgatoWaveAPI/bin/Release/net6.0/

            - name: List Files
              run: dir /s /b /o:gn
              working-directory: ElgatoWaveAPI/bin/Release/net6.0/

            - name: Package
              run: dotnet pack --configuration Release --no-restore --version-suffix ${{ env.betaVersion }}
              
            - name: Publish
              run: dotnet nuget push "*.nupkg" --api-key ${{secrets.NUGETAPI}} --no-symbols --skip-duplicate --source https://api.nuget.org/v3/index.json

    release:
        name: Release
        if: ${{ github.event_name != 'pull_request' }}
        runs-on: windows-latest
        needs: beta-release
        environment:
            name: release
        steps:
            - name: Download artifacts
              uses: actions/download-artifact@v3
              with:
                name: artifact
                path: ElgatoWaveAPI/bin/Release/net6.0/

            - name: List Files
              run: dir /s /b /o:gn
              working-directory: ElgatoWaveAPI/bin/Release/net6.0/

            - name: Package
              run: dotnet pack --configuration Release --no-restore
              
            - name: Publish
              run: dotnet nuget push "*.nupkg" --api-key ${{secrets.NUGETAPI}} --no-symbols --skip-duplicate --source https://api.nuget.org/v3/index.json