name: Pipeline

on:
    workflow_dispatch:
        inputs:
            version:
                required: true
                description: Input version for this build

    push:
        branches: ["main"]
        paths-ignore:
            - '**/*.md'
            - '**/*.gitignore'
            - '**/*.gitattributes'
    pull_request:
        branches: ["main"]
        paths-ignore:
            - '**/*.md'
            - '**/*.gitignore'
            - '**/*.gitattributes'

#Not sure if I want this to cancel the previous build yet
#concurrency:
#  group: ${{ github.workflow }}-${{ github.ref }}
#  cancel-in-progress: true

jobs:
    build:
        name: Build
        runs-on: windows-latest
        environment:
            name: beta
        steps:
            - uses: actions/checkout@v3

            - name: Setup .Net
              uses: actions/setup-dotnet@v2
              with:
                dotnet-version: 6.x

            - name: Restore
              run: dotnet restore

            - name: Version Bump
              #if: ${{ github.event.inputs.version == '' }}
              uses: SiqiLu/dotnet-bump-version@master
              with:
                version_files: 'ElgatoWaveAPI\ElgatoWaveSDK.csproj'
                github_token: ${{ secrets.GITHUBTOKEN }}

            - name: Build
              run: dotnet build --configuration Release --no-restore --version-suffix beta-${{ github.run_number }}

            - name: Test
              run: dotnet test --no-build -c Release --no-restore --collect "Code coverage" --blame

            - name: Upload Artifacts
              uses: actions/upload-artifact@v3
              with:
                name: artifact
                if-no-files-found: error
                retention-days: 5
                path: |
                    ElgatoWaveAPI/bin/Release/net6.0/
                    ElgatoWaveAPI/bin/Release/*.nupkg
              
            - name: Publish Pre-Release
              if: github.event.pull_request.merged == false
              run: dotnet nuget push "ElgatoWaveAPI\bin\Release\*.nupkg" --api-key ${{secrets.NUGETAPI}} --no-symbols --skip-duplicate --source https://api.nuget.org/v3/index.json

    #release:
    #    name: Publish
    #    needs: build
    #    runs-on: windows-latest
    #    environment:
    #        name: release
    #    steps:

    #        - name: Download Artifacts
    #          uses: actions/download-artifact@v3
    #          with:
    #            name: artifact
    #            path: artifactDownload

            #- name: Nugest Package

            #- name: Publich Nuget