name: Tests Only

on:
    workflow_dispatch:

env:
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    SONAR_PROJECT_KEY: "Professor-Melvin_ElgatoWaveLinkSDK"
    SONAR_PROJECT_NAME: "ElgatoWaveLinkSDK"
    SONAR_ORG_NAME: "professor-melvin"

jobs:
    test:
        name: Test
        runs-on: windows-latest
        environment:
            name: pr
        steps:
            - uses: actions/checkout@v3

            - name: Setup .Net
              uses: actions/setup-dotnet@v2
              with:
                dotnet-version: 6.x

            - name: Restore
              run: dotnet restore

            - name: Build Beta
              run: dotnet build --configuration Release --no-restore

            #- name: Test
            #  run: dotnet test --no-build -c Release --no-restore --collect "Code coverage" --blame

            - name: SonarScanner for .NET 6 with pull request decoration support
              uses: highbyte/sonarscan-dotnet@v2.1.3
              with:
                sonarProjectKey: ${{ SONAR_PROJECT_KEY }}
                sonarProjectName:  ${{ SONAR_PROJECT_NAME }}
                sonarOrganization: ${{ SONAR_ORG_KEY }}
                dotnetTestArguments: --no-build -c Release --no-restore --logger trx --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
                sonarBeginArguments: /d:sonar.cs.opencover.reportsPaths="**/TestResults/**/coverage.opencover.xml" -d:sonar.cs.vstest.reportsPaths="**/TestResults/*.trx"        